apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: skinny-cod-nodejs 
  janus-idp.io/tekton: skinny-cod-nodejs
  backstage.io/kubernetes-id: skinny-cod-nodejs
  backstage.io/kubernetes-namespace: rhtap-e2e-ci 
  app.kubernetes.io/part-of: skinny-cod-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  